// dumper.cpp
#include "dumper.h"
#include "utils.h"

namespace Dumper {
	// --- Private Helper for C++ Type Generation ---
	std::string GetCTypeAndSize(Il2CppType* type, uint32_t& outSize) {
		if (!type) { outSize = 8; return "void*"; }

		uint8_t typeEnum = Il2Cpp::GetTypeEnum(type);
		outSize = 8; // Default pointer size (x64)

		switch (typeEnum) {
		case IL2CPP_TYPE_VOID:    outSize = 0; return "void";
		case IL2CPP_TYPE_BOOLEAN: outSize = 1; return "bool";
		case IL2CPP_TYPE_I1:      outSize = 1; return "int8_t";
		case IL2CPP_TYPE_U1:      outSize = 1; return "uint8_t";
		case IL2CPP_TYPE_I2:      outSize = 2; return "int16_t";
		case IL2CPP_TYPE_U2:      outSize = 2; return "uint16_t";
		case IL2CPP_TYPE_CHAR:    outSize = 2; return "uint16_t"; // UTF-16
		case IL2CPP_TYPE_I4:      outSize = 4; return "int32_t";
		case IL2CPP_TYPE_U4:      outSize = 4; return "uint32_t";
		case IL2CPP_TYPE_R4:      outSize = 4; return "float";
		case IL2CPP_TYPE_I8:      outSize = 8; return "int64_t";
		case IL2CPP_TYPE_U8:      outSize = 8; return "uint64_t";
		case IL2CPP_TYPE_R8:      outSize = 8; return "double";
		case IL2CPP_TYPE_I:
		case IL2CPP_TYPE_U:       outSize = 8; return "intptr_t";

		case IL2CPP_TYPE_STRING:  outSize = 8; return "struct Il2CppString*";
		case IL2CPP_TYPE_OBJECT:  outSize = 8; return "struct Il2CppObject*";

			// === STRUCTS (Value Types) ===
			// Stored "inline".
		case IL2CPP_TYPE_VALUETYPE:
		{
			Il2CppClass* klass = Il2Cpp::class_from_type(type);
			if (klass) {
				std::string safeName = Utils::SanitizeName(Il2Cpp::class_get_name(klass));
				std::string ns = Utils::SanitizeName(Il2Cpp::class_get_namespace(klass));
				if (!ns.empty()) safeName = ns + "_" + safeName;

				// Il2Cpp "Class Size" includes header (0x10 bytes: vtable + monitor)
				uint32_t boxedSize = Il2Cpp::GetClassSize(klass);

				// Subtract header to get real data size
				if (boxedSize > 0x10) outSize = boxedSize - 0x10;
				else outSize = 1;

				return "struct " + safeName;
			}
			return "void*";
		}

		// === CLASSES & ARRAYS (Reference Types) ===
		case IL2CPP_TYPE_CLASS:
		case IL2CPP_TYPE_SZARRAY:
		case IL2CPP_TYPE_ARRAY:
		case IL2CPP_TYPE_GENERICINST:
		{
			Il2CppClass* klass = Il2Cpp::class_from_type(type);
			if (klass) {
				std::string safeName = Utils::SanitizeName(Il2Cpp::class_get_name(klass));
				std::string ns = Utils::SanitizeName(Il2Cpp::class_get_namespace(klass));
				if (!ns.empty()) safeName = ns + "_" + safeName;
				return "struct " + safeName + "*";
			}
			return "void*";
		}
		case IL2CPP_TYPE_PTR: return "void*";
		default: return "void*";
		}
	}

	void CollectAllClasses(std::vector<Il2CppClass*>& output) {
		__try {
			for (int32_t i = 0; ; ++i) {
				Il2CppClass* cls = Il2Cpp::MetadataCache__GetTypeInfoFromTypeDefinitionIndex(i);
				if (!cls) break;
				output.push_back(cls);
			}
		}
		__except (EXCEPTION_EXECUTE_HANDLER) {
			Utils::Log("Exception raised, collected %d classes\n", output.size());
		}
	}

	void GenerateSDK() {
		FILE* file;
		fopen_s(&file, "structs.h", "w");
		if (!file) return;

		fprintf(file, "// Generated by GIRuntimeDumper\n#pragma once\n#include <cstdint>\n\n");
		fprintf(file, "struct Il2CppString { struct Il2CppObject* obj; int32_t length; char chars[1]; };\n\n");

		Utils::Log("Collecting classes for struct dump...\n");
		std::vector<Il2CppClass*> allClasses;
		CollectAllClasses(allClasses);

		// Forward Declarations
		Utils::Log("Writing forward declarations...\n");
		for (Il2CppClass* cls : allClasses) {
			std::string name = Il2Cpp::class_get_name(cls);
			std::string ns = Il2Cpp::class_get_namespace(cls);
			std::string fullName = Utils::SanitizeName(ns.empty() ? name : ns + "_" + name);
			fprintf(file, "typedef struct %s %s;\n", fullName.c_str(), fullName.c_str());
		}
		fprintf(file, "\n");

		// Definitions
		Utils::Log("Writing definitions...\n");
		for (Il2CppClass* cls : allClasses) {
			std::string name = Il2Cpp::class_get_name(cls);
			std::string ns = Il2Cpp::class_get_namespace(cls);
			std::string fullName = Utils::SanitizeName(ns.empty() ? name : ns + "_" + name);

			std::string parentName = "Il2CppObject";
			Il2CppClass* parentClass = Il2Cpp::GetClassParent(cls);
			if (parentClass) {
				std::string pName = Il2Cpp::class_get_name(parentClass);
				std::string pNs = Il2Cpp::class_get_namespace(parentClass);
				parentName = Utils::SanitizeName(pNs.empty() ? pName : pNs + "_" + pName);
			}

			// ENUM HANDLING
			if (parentName == "System_Enum") {
				void* iter = nullptr;
				FieldInfo* valueField = nullptr;
				int enumCount = 0;
				while (FieldInfo* f = Il2Cpp::class_get_fields(cls, &iter)) {
					if (strcmp(Il2Cpp::field_get_name(f), "value__") == 0) valueField = f;
					else ++enumCount;
				}

				if (!valueField) continue;

				uint32_t typeSize = 0;
				std::string backingType = GetCTypeAndSize(Il2Cpp::field_get_type(valueField), typeSize);
				uint8_t typeEnum = Il2Cpp::GetTypeEnum(Il2Cpp::field_get_type(valueField));

				fprintf(file, "// Namespace: %s\nenum class %s : %s {\n", ns.c_str(), fullName.c_str(), backingType.c_str());

				iter = nullptr;
				int index = 0;
				while (FieldInfo* f = Il2Cpp::class_get_fields(cls, &iter)) {
					if (f == valueField) continue;
					fprintf(file, "    %s = ", Il2Cpp::field_get_name(f));
					uint64_t raw = Il2Cpp::vm__GetEnumFieldValue(cls, f);

					// Format based on type (simplified)
					switch (typeEnum) {
					case IL2CPP_TYPE_I1:
						fprintf(file, "%d", (int8_t)raw);
						break;
					case IL2CPP_TYPE_U1:
						fprintf(file, "%u", (uint8_t)raw);
						break;
					case IL2CPP_TYPE_I2:
						fprintf(file, "%d", (int16_t)raw);
						break;
					case IL2CPP_TYPE_U2:
						fprintf(file, "%u", (uint16_t)raw);
						break;
					case IL2CPP_TYPE_I4:
						fprintf(file, "%d", (int32_t)raw);
						break;
					case IL2CPP_TYPE_U4:
						fprintf(file, "%u", (uint32_t)raw);
						break;
					case IL2CPP_TYPE_I8:
						fprintf(file, "%lld", (int64_t)raw);
						break;
					case IL2CPP_TYPE_U8:
						fprintf(file, "%llu", (uint64_t)raw);
						break;
					default:
						// unreachable
						break;
					}

					if (++index < enumCount) fprintf(file, ",\n");
				}
				fprintf(file, "\n};\n\n");
			}
			// STRUCT HANDLING
			else {
				fprintf(file, "// Namespace: %s\nstruct %s : %s {\n", ns.c_str(), fullName.c_str(), parentName.c_str());

				void* iter = nullptr;
				while (FieldInfo* field = Il2Cpp::class_get_fields(cls, &iter)) {
					int flags = Il2Cpp::field_get_flags(field);
					if (flags & FIELD_ATTRIBUTE_STATIC) continue;

					std::string fName = Il2Cpp::field_get_name(field);
					std::replace(fName.begin(), fName.end(), '<', '_');
					std::replace(fName.begin(), fName.end(), '>', '_');

					uint32_t typeSize = 0;
					std::string typeStr = GetCTypeAndSize(Il2Cpp::field_get_type(field), typeSize);
					int32_t offset = Il2Cpp::field_get_offset(field);

					fprintf(file, "    %s %s; // 0x%X\n", typeStr.c_str(), fName.c_str(), offset);
				}
				fprintf(file, "};\n\n");
			}
		}
		fclose(file);
		Utils::Log("Struct dump completed: structs.h\n");
	}

	void DumpFull() {
		Utils::Log("Collecting classes for full dump...\n");
		std::vector<Il2CppClass*> allClasses;
		CollectAllClasses(allClasses);

		for (Il2CppClass* cls : allClasses) {
			// Simplified for brevity, logic remains identical to original
			std::string name = Il2Cpp::class_get_name(cls);
			std::string ns = Il2Cpp::class_get_namespace(cls);

			Il2CppClass* parent = Il2Cpp::GetClassParent(cls);
			std::string parentStr = parent ? Il2Cpp::class_get_name(parent) : "";

			Utils::Log("// Namespace: %s\nclass %s : %s\n{\n", ns.c_str(), name.c_str(), parentStr.c_str());
			//Utils::Log("// TypeDefIndex: %d\n// Namespace: %s\nclass %s : %s\n{\n", i, ns.c_str(), name.c_str(), parentStr.c_str());

			// Fields
			void* iter = nullptr;
			while (FieldInfo* f = Il2Cpp::class_get_fields(cls, &iter)) {
				int flags = Il2Cpp::field_get_flags(f);
				std::string typeName = Utils::StripNamespaces(Il2Cpp::GetTypeName(Il2Cpp::field_get_type(f)));
				Utils::Log("\t%s %s; // Offset: 0x%X, Flags: 0x%X\n", typeName.c_str(), Il2Cpp::field_get_name(f), Il2Cpp::field_get_offset(f), flags);
			}

			// Methods
			iter = nullptr;
			Utils::Log("\n\t// Methods\n");
			while (MethodInfo* m = Il2Cpp::class_get_methods(cls, &iter)) {
				std::string retType = Utils::StripNamespaces(Il2Cpp::GetTypeName(Il2Cpp::method_get_return_type(m)));
				std::string params = "";
				uint8_t count = Il2Cpp::GetMethodParamCount(m);
				for (uint8_t p = 0; p < count; p++) {
					params += Utils::StripNamespaces(Il2Cpp::GetTypeName(Il2Cpp::method_get_param(m, p)));
					params += " ";
					params += Il2Cpp::method_get_param_name(m, p);
					if (p < count - 1) params += ", ";
				}

				Utils::Log("\t%s %s(%s); // RVA: 0x%llX\n", retType.c_str(), Il2Cpp::method_get_name(m), params.c_str(), Il2Cpp::GetMethodPointer(m) - Config::GameBase);
			}
			Utils::Log("}\n\n");
		}
	}
}